[project]
channels = ["pytorch", "nvidia", "conda-forge"]
description = "Add a short description here"
name = "template"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
linux = "4.18"
cuda = "11"

[tasks]

[dependencies]
pytorch = ">=2.5.1,<3"
lightning = ">=2.5.0.post0,<3"
torchmetrics = ">=1.6.1,<2"
torchvision = ">=0.20.1,<0.21"
matplotlib = ">=3.9.1,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.1,<3"
pyrootutils = ">=1.0.4,<2"
hydra-core = ">=1.3.2,<2"
pytorch-cuda = ">=12,<13"
webdataset = ">=0.2.100,<0.3"
