- datamodule.batch_size=64
- datamodule.num_workers=3
- module.lr=1e-2
- module.momentum=0.0
- module.nesterov=false
- module.weight_decay=0.0
- module.use_pretrained= false
- module.fine_tune= true
- trainer.num_nodes=1
- trainer.precision=32-true
- trainer.max_epochs=10
- trainer.accelerator=auto
- trainer.strategy=auto
- trainer.devices=auto
- trainer.sync_batchnorm=false
- trainer.gradient_clip_val=null
- trainer.gradient_clip_algorithm=norm
- trainer.profiler=simple
- paths.output_dir=out/2025-01-27_22-17-59
- paths.data_dir=/home/angelos.toutsios.gr/data/CS4321/HW1/teamsmt/data
