hydra:
  run:
    dir: ${paths.output_dir}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath: []
  callbacks: {}
  output_subdir: configs
  overrides:
    hydra:
    - hydra.run.dir=${paths.output_dir}
    - hydra.mode=RUN
    task:
    - datamodule.batch_size=64
    - datamodule.num_workers=3
    - module.lr=1e-2
    - module.momentum=0.0
    - module.nesterov=false
    - module.weight_decay=0.0
    - module.use_pretrained= false
    - module.fine_tune= true
    - trainer.num_nodes=1
    - trainer.precision=32-true
    - trainer.max_epochs=10
    - trainer.accelerator=auto
    - trainer.strategy=auto
    - trainer.devices=auto
    - trainer.sync_batchnorm=false
    - trainer.gradient_clip_val=null
    - trainer.gradient_clip_algorithm=norm
    - trainer.profiler=simple
    - paths.output_dir=out/2025-01-27_22-30-55
    - paths.data_dir=/home/angelos.toutsios.gr/data/CS4321/HW1/teamsmt/data
  job:
    name: train
    chdir: null
    override_dirname: datamodule.batch_size=64,datamodule.num_workers=3,module.fine_tune=
      true,module.lr=1e-2,module.momentum=0.0,module.nesterov=false,module.use_pretrained=
      false,module.weight_decay=0.0,paths.data_dir=/home/angelos.toutsios.gr/data/CS4321/HW1/teamsmt/data,paths.output_dir=out/2025-01-27_22-30-55,trainer.accelerator=auto,trainer.devices=auto,trainer.gradient_clip_algorithm=norm,trainer.gradient_clip_val=null,trainer.max_epochs=10,trainer.num_nodes=1,trainer.precision=32-true,trainer.profiler=simple,trainer.strategy=auto,trainer.sync_batchnorm=false
    id: ???
    num: ???
    config_name: COASTresnet50.yaml
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /data/angelos.toutsios.gr/CS4321/HW1/teamsmt
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /data/angelos.toutsios.gr/CS4321/HW1/teamsmt/configs
      schema: file
      provider: main
    - path: /data/angelos.toutsios.gr/CS4321/HW1/teamsmt/configs
      schema: file
      provider: command-line
    - path: ''
      schema: structured
      provider: schema
    output_dir: /data/angelos.toutsios.gr/CS4321/HW1/teamsmt/out/2025-01-27_22-30-55
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
